set -g prefix C-a

unbind %
bind | split-window -h
bind - split-window -v
bind C-Left resize-pane -L 20
bind C-Right resize-pane -R 20


# Set status bar
set -g status-bg colour235
set -g status-fg white
set -g status-left '#[bg=color19,fg=color87] #(echo "#{session_name}" | tr "[:lower:]" "[:upper:]") #[default] '

# Highlight active window
set-window-option -g window-status-current-style bg=color121,fg=black,bold

# Make control keys work
set-window-option -g xterm-keys on

set escape-time 50

set -g status-right '#[fg=green] | %Y-%m-%d #[fg=white]%H:%M#[default]'
